# Guided Exploration No. 3
# Bane Gorsage
# to import the random module
import random
# this is to store the rap names from rap-names.txt file.
possible_names = []
# to open a file and store the names generated by the program.
outputFile = open('rap-names-output.txt', 'w')
# it opens the file and reads it. Then it sends a handle to dataFile.
with open('rap-names.txt', 'r') as dataFile:
    # It's to assign dataFile to a varible and loop through it.
    for name in dataFile:
        # this will add the rap names in the file to the possible_names list using the name varible.
        possible_names.append(name.rstrip())
# this ask how  many names does the user want to enter and assigns that number to the varible 'count'
count = int(input('How many rap names would you like to create? '))
# This ask how many parts does the name have and assigns it to the varible 'parts'
parts = int(input('How many parts should the name contain? '))
# this is to generate the total number of rap names the user wants
for i in range(count):
    # this is another blank list that will hold the 'parts' that the user entered.
    name_parts = []
    # It iterates the number of rap names that the user wants as part of the names.
    for j in range(parts):
        # This is to show that the code needs to generate a random number so it can get the rap name from the possible_names list.
        # The random.randint() method needs a to generate this number from 0 to the length of the possible_names list and then subtract one from it.
        name_parts.append(
            possible_names[random.randint(0, len(possible_names)-1)])
        # This code is going to take the handle to the file where we are going to write out the generated rap names too.
        outputFile.write(f"{' '.join(name_parts)}\n")
        # This is to print out {' '.join(name_parts)}"
        print(f"{' '.join(name_parts)}")
# This is to close the file
outputFile.close()
